name = "duckie-productivity-mcp-server"
main = "src/index.ts"
compatibility_date = "2024-12-01"
[ai]
binding = "AI"
[[d1_databases]]
binding = "DB"
database_name = "duckie-db"
database_id = "your-database-id-here"
[vars]
NODE_ENV = "production"
